config/routes.rb
Rails.application.routes.draw do
  resources :locations, except: [:show,:edit,:update,:destroy]
  resources :car_costs, except: [:show,:destroy]
  resources :tokens 
  get 'status_search' ,  to:'tokens#status_search'
  get 'admin/admin'
  get 'approve_status', to: 'admin#approve_appointment'
  resources :models, except: [:show]
  resources :kilometer_drivens, except: [:show]
  resources :variants, except: [:show]
 
  resources :registration_years, only: [:index]
  resources :registration_states, except: [:show]
  resources :brands, except: [:show]
  resources :cities, except: [:show]
  resources :sellers do 
              collection do
                get 'search_city'
                get 'search_brand'
                get 'search_registration_year'
                get 'search_variant'
                get 'search_registration_state'
                get 'search_kilometer_driven'
                get 'search_model'
                get 'update_status'
                get 'my_add'

              end
              member do
                get :toggle_status
                get :approve
                get :reject
              end
            end
  resources :users, except: [:new,:show] do
    member do
      get 'confirm_email'
    end
  end
  get '/signup', to: 'users#new'
  root to: 'pages#home'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/seller.rb
class Seller < ApplicationRecord

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :brand,              foreign_key: "brand_id"
  belongs_to :user,               foreign_key: "user_id"
  belongs_to :city,               foreign_key: "city_id"
  belongs_to :kilometer_driven,   foreign_key: "kilometer_driven_id"
  belongs_to :registration_state, foreign_key: "registration_state_id"
  belongs_to :registration_year,  foreign_key: "registration_year_id"
  belongs_to :model,              foreign_key: "model_id"
  belongs_to :variant,            foreign_key: "variant_id"

  has_many :tokens

  validates :brand_id,              presence: true
  validates :registration_state_id, presence: true
  validates :city_id,               presence: true
  validates :kilometer_driven_id,   presence: true
  validates :registration_year_id,  presence: true 
  validates :model_id,              presence: true
  validates :variant_id,            presence: true
  validates :user_id,               presence: true

  scope :car_model,            -> car_model_name            { includes(:model).where(models: {name: car_model_name} ) }
  scope :car_city,             -> car_city_name             { includes(:city).where(cities: {name: car_city_name} ) }
  scope :car_brand,            -> car_brand_name            { includes(:brand).where(brands: {name: car_brand_name}) }
  scope :car_reg_year,         -> car_reg_year_name         { includes(:registration_year).where(registration_years: { name: car_reg_year_name }) }
  scope :car_kilometer_driven, -> car_kilometer_driven_name { includes(:kilometer_driven).where(kilometer_drivens: {name: car_kilometer_driven_name})}
  scope :car_variant,          -> car_variant_name          { includes(:variant).where(variants: {name: car_variant_name }) }
  scope :car_reg_state,        -> car_reg_state_name        { includes(:registration_state).where(registration_states: { name:  car_reg_state_name }) }

  def as_indexed_json(options = {})
    self.as_json(only: [:id],
      include: {
        city: { only: [:name] },
        model: { only: [:name] },
        variant: { only: [:name] },
        brand: { only: [:name] },
        registration_state: { only: [:name] }
      }
    )
  end

  searchkick

  def search_data
    {
      city: city.name,
      model: model.name,
      registration_year: registration_year.name,
      variant: variant.name,
      kilometer_driven: kilometer_driven.name,
      registration_state: registration_state.name,
      brand: brand.name
    }
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :require_login 
  before_action :require_admin ,only: [:approve, :reject],except: [:approve, :reject,:update_status,:my_add]
  before_action :require_buyer, except: [:create,:new,:approve, :reject,:update_status,:my_add]
  before_action :require_seller, only: [:create,:new,:approve, :reject,:update_status,:my_add]
   include ApplicationHelper

  def index
    if params[:search].present?
      query = params[:search]
      @sellers =   Seller.search(query)
    else
      @sellers = Seller.all
    end
  end 

  def new
    @seller = Seller.new
  end

  def search_city
    @sellers = Seller.all
    @sellers = @sellers.car_city( params[:city_name]) if params[:city_name].present?
    @sellers = @sellers.car_model( params[:model_name]) if params[:model_name].present?
    @sellers = @sellers.car_brand( params[:brand_name]) if params[:brand_name].present?
    @sellers = @sellers.car_reg_year( params[:registration_year_name]) if params[:registration_year_name].present?
    @sellers = @sellers.car_kilometer_driven( params[:kilometer_driven_name]) if params[:kilometer_driven_name].present?
    @sellers = @sellers.car_variant( params[:variant_name]) if params[:variant_name].present?
    @sellers = @sellers.car_reg_state( params[:registration_state_name]) if params[:registration_state_name].present?
    @sellers
  end

  def create
  @seller = Seller.new(seller_params)
  @seller.user_id = current_user.id
    if @seller.save
      redirect_to new_token_path, notice: 'Generate appointment.' 
    else
      render :new
    end
  end

  def approve
    @seller = Seller.find(params[:id])
    @seller.purchase_status="Sold"
    @seller.save
    ApprovePurchaseWorker.perform_async(@seller.id)
    @approve= @seller.tokens
    @approve.each do |p|
      p.status = "SOLD"
      p.save
    end
    redirect_to update_status_sellers_path
  end

  def reject
    @seller = Seller.find(params[:id]) 
    @seller.purchase_status="purchase"
    @seller.save
    RejectPurchaseWorker.perform_async(@seller.id)
    redirect_to update_status_sellers_path
  end

def toggle_status
    @seller = Seller.find(params[:id])
  if @seller.purchase_status == "purchase" 
    @seller.purchase_status = "cancel purchase"
    @seller.buyer_id = current_user.id
    @seller.save
    PurchaseNotifyWorker.perform_async(@seller.id)
  elsif @seller.purchase_status == "cancel purchase" 
    @seller.purchase_status = "purchase"
    @seller.buyer_id = current_user.id
    RejectNotifyWorker.perform_async(@seller.id)
    @seller.save
  end
  redirect_to sellers_path 
end

  def update_status
    @updates = Seller.all.where(purchase_status:"cancel purchase", user_id: current_user.id)
  end

  def my_add
    @post = Seller.all.includes(:tokens).where(user_id: current_user.id)
  end

  def show
    @search = Token.all.where(id: params[:q])
  end

private

  def seller_params
    params.require(:seller).permit(:city_id, :brand_id, :model_id, :registration_year_id, :registration_state_id, :variant_id, :kilometer_driven_id,:token_id, :user_id, :buyer_id)
  end
end

app/views/sellers/_form.html.erb
<div class="container mt-5 py-4 card shadow-lg p-3 mb-5 bg-white rounded">
<%= form_with(model: seller, local: true) do |form| %>
  <%= render 'shared/error',obj: @seller %>
  <div class="row">
    <div class="col-md-6">
      <div class="field ">
         <%= collection_select(:seller, :city_id, City.all, :id, :name, {prompt: 'Please select your car city'}, {class: 'form-control '}) %>
      </div>
      <div class="field">
        <%= collection_select(:seller, :brand_id, Brand.all, :id, :name, {prompt: 'Please select your car Brand'}, {class: 'form-control '}) %>
      </div>
      <div class="field">
        <%= collection_select(:seller, :model_id, Model.all, :id, :name, {prompt: 'Please select your car Model'}, {class: 'form-control '}) %>
      </div>
      <div class="field">
        <%= collection_select(:seller, :registration_year_id, RegistrationYear.all, :id, :name,  {prompt: 'Please select your car Registration Year'} , {class:'form-control '}) %>
      </div>
    </div>
    <div class="col-md-6">  
      <div class="field">
        <%= collection_select(:seller, :registration_state_id, RegistrationState.all, :id, :name,  {prompt: 'Please select your car Registration state'}, {class: 'form-control '}) %>
      </div>
      <div class="field">
        <%= collection_select(:seller, :variant_id, Variant.all, :id, :name, {prompt: 'Please select your car Variant'}, {class: 'form-control '}) %>
      </div>
      <div class="field">
        <%= collection_select(:seller, :kilometer_driven_id, KilometerDriven.all, :id, :name,  {prompt: 'Please select your car Kilometer Driven'}, {class: 'form-control '}) %>
      </div>
    </div>
  </div>    
  <div class="actions text-center mt-4  ">
    <%= form.submit 'post add', class: " shadow-sm p-3 mb-5  rounded"%>
  </div>
  <% end %>
</div>

app/views/sellers/_search.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">City</th>
      <th scope="col">Model</th>
      <th scope="col">Brand</th>
      <th scope="col">Kilometer-Driven</th>
      <th scope="col">Registration-Year</th>
      <th scope="col">Registration-State</th>
      <th scope="col">Variant</th>
      <th> Price </th>
      <th scope="col">Buy</th>
    </tr>
  </thead>
  <tbody>
    <% @sellers.each do |seller| %>
      <% seller.tokens.each do |token| %>
        <% if token.status == 'APPROVE'  %>
          <% if ( (seller.purchase_status == "cancel purchase") and  (seller.buyer_id == current_user.id) ) or (seller.purchase_status == "purchase")  %>
        <tr>
          <td><%= seller.city.name %></td>
          <td><%= seller.model.name %></td>
          <td><%= seller.brand.name %></td>
          <td><%= seller.kilometer_driven.name %></td>
          <td><%= seller.registration_year.name %></td>
          <td><%= seller.registration_state.name %></td>
          <td><%= seller.variant.name %></td>
          <td> <%= seller.tokens.last.car_cost.price%> </td>
          <td> <%= link_to seller.purchase_status, toggle_status_seller_path(seller) , class: "btn btn-dark px-3" %></td>     
        </tr>
          <% end %>
        <%end%>
      <%end%>
    <% end %>
  </tbody>
</table>
<div class="text-center my-3 p-2">
  <%= link_to 'Back to home', root_path, class: "btn btn-primary rounded-pill" %>
</div>

app/views/sellers/_update.html.erb
<tr id="buyer-<%= seller.id%>">
  <td><%= seller.city.name %></td>
  <td><%= seller.model.name %></td>
  <td><%= seller.brand.name %></td>
  <td><%= seller.kilometer_driven.name %></td>
  <td><%= seller.registration_year.name %></td>
  <td><%= seller.registration_state.name %></td>
  <td><%= seller.variant.name %></td>
  <td><%= link_to 'Approve', approve_seller_path(seller) ,class: "nav-link  btn btn-warning p-1 btn-lg" %></td>
  <td><%= link_to 'Reject', reject_seller_path(seller) ,class: "nav-link  btn btn-danger p-1 btn-lg" %></td>
</tr>

app/views/sellers/edit.html.erb
<h1>Editing Seller</h1>

<%= render 'form', seller: @seller %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', sellers_path %>

app/views/sellers/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'shared/category_search' %>
<%= render 'sellers/search' %>

app/views/sellers/my_add.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">City</th>
      <th scope="col">Model</th>
      <th scope="col">Brand</th>
      <th scope="col">Kilometer-Driven</th>
      <th scope="col">Registration-Year</th>
      <th scope="col">Registration-State</th>
      <th scope="col">Variant</th>
      <th scope="col">Status</th>
      <th scope="col"> Car Condition</th> 
      <th scope="col">Car Cost</th>
    </tr>
  </thead>
  <tbody id="add-post">
    <% @post.each do |seller| %>
      <%= render 'posts/post', seller: seller %>
    <% end %> 

  </tbody>
</table>
<div class="text-center my-3 p-2">
  <%= link_to 'Back to home', root_path, class: "btn btn-primary rounded-pill" %>
</div>

app/views/sellers/new.html.erb
<h1 class=" card-header" align="center">Enter the details of your car</h1>
<%= render 'form', seller: @seller %>
<%= link_to 'Back', root_path %>

app/views/sellers/search_city.html.erb
<%= render 'shared/category_search' %>
<h1>Search City year result</h1>
<%= render 'sellers/search' %>

app/views/sellers/show.html.erb
<div class="card">
<div class="card-body">
  <div class="card-header">
    <div class="text-center bg-dark text-white display-4">Search result</div>
  </div>
  <div class="card-body text-center">
    <% if @search.empty? %>
      <h4 class="display-4 card-text">Enter a valid id</h4>  
    <%else%>
      <% @search.each do |search| %>
        <% if search.user_id == current_user.id %>
          <div class= "h2">
            Status of your appointment is : <span class="display-4 px-3"><%= search.status.upcase %></span>
          </div>
        <% else %>
          <h3 class="display-4">This ID does't belongs to you</h3>
        <% end %>
      <% end %>
    <%end%>
  </div>
</div>
</div>

app/views/sellers/update_status.html.erb
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">City</th>
        <th scope="col">Model</th>
        <th scope="col">Brand</th>
        <th scope="col">Kilometer-Driven</th>
        <th scope="col">Registration-Year</th>
        <th scope="col">Registration-State</th>
        <th scope="col">Variant</th>
      </tr>
    </thead>
    <tbody id="buy-car"  value =<%= current_user.id %>>
      <% @updates.each do |seller| %>
        <%= render 'sellers/update' ,seller: seller %>
      <% end %>
    </tbody>
  </table>
  <div class="text-center my-3 p-2">
    <%= link_to 'Back to home', root_path, class: "btn btn-primary rounded-pill" %>
  </div>