config/routes.rb
Rails.application.routes.draw do
  resources :locations, except: [:show,:edit,:update,:destroy]
  resources :car_costs, except: [:show,:destroy]
  resources :tokens 
  get 'status_search' ,  to:'tokens#status_search'
  get 'admin/admin'
  get 'approve_status', to: 'admin#approve_appointment'
  resources :models, except: [:show]
  resources :kilometer_drivens, except: [:show]
  resources :variants, except: [:show]
 
  resources :registration_years, only: [:index]
  resources :registration_states, except: [:show]
  resources :brands, except: [:show]
  resources :cities, except: [:show]
  resources :sellers do 
              collection do
                get 'search_city'
                get 'search_brand'
                get 'search_registration_year'
                get 'search_variant'
                get 'search_registration_state'
                get 'search_kilometer_driven'
                get 'search_model'
                get 'update_status'
                get 'my_add'

              end
              member do
                get :toggle_status
                get :approve
                get :reject
              end
            end
  resources :users, except: [:new,:show] do
    member do
      get 'confirm_email'
    end
  end
  get '/signup', to: 'users#new'
  root to: 'pages#home'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/admin.html.erb
<div class="container home">
  <h2 class="display -2 mx-auto">Welcome to admin page</h2>
  <div class="d-flex flex-column">
    <div class="card my-3">
      <%= link_to 'City page', cities_path, class: "btn btn-info" %>
    </div>
    <div class="card my-3">
      <%= link_to 'Model page', models_path, class: "btn btn-info" %>
    </div>
    <div class="card my-3">
      <%= link_to 'Registration year', registration_years_path, class: "btn btn-info" %>
    </div>

    <div class="card my-3">
      <%= link_to ' variant page', variants_path, class: "btn btn-info" %>
    </div> 
    <div class="card my-3">
      <%= link_to ' Brand page', brands_path, class: "btn btn-info" %>
    </div>
    <div class="card my-3">
      <%= link_to ' Registration state page' , registration_states_path, class: "btn btn-info" %>
    </div>
    <div class="card my-3">
      <%= link_to ' Kilometer Driven page', kilometer_drivens_path, class: "btn btn-info" %>
    </div>
  
    <% if CarCost.last.nil? %>
        <%= link_to 'You need to set FOUR  car cost condition first', car_costs_path, class: "btn btn-info" %>
    <% else %>      
      <div class="card my-3">
        <%= link_to 'Car cost page', car_costs_path, class: "btn btn-info" %>
      </div>
    <%end%>
  </div>
</div>

app/views/admin/approve_appointment.html.erb
<h1> Approve status </h1>

    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">City</th>
      <th scope="col">Model</th>
      <th scope="col">Brand</th>
      <th scope="col">Kilometer-Driven</th>
      <th scope="col">Registration-Year</th>
      <th scope="col">Registration-State</th>
      <th scope="col">Variant</th>
      <th scope="col">Appointment date</th>
      <% if logged_in? && current_user.role.roles == "ADMIN"%>
      <th scope="col">Appointment status</th>
      <%end%>
    </tr>
  </thead>
<% @sellers.each do |seller|  %>
    <% seller.tokens.where(status: "processing").each do |token| %>
    <% s = token.seller %>

  <tbody>
    <tr>
        <td><%= s.city.name %></td>
        <td><%= s.model.name %></td>
        <td><%= s.brand.name %></td>
        <td><%= s.kilometer_driven.name %></td>
        <td><%= s.registration_year.name %></td>
        <td><%= s.registration_state.name %></td>
        <td><%= s.variant.name %></td>
        <td><%= token.appointment_date.strftime("%a, %d %b %Y ") if token.appointment_date %> </td>
    <td><%= link_to 'Change status', edit_token_path(token) ,class: "nav-link  btn btn-info p-1 " %></td>
    </tr>
  </tbody>
    <% end %>
<% end %>
</table>
<div class="text-center my-3 p-2">
  <%= link_to 'Back to home', root_path, class: "btn btn-primary rounded-pill" %>
</div>