config/routes.rb
Rails.application.routes.draw do
  resources :locations, except: [:show,:edit,:update,:destroy]
  resources :car_costs, except: [:show,:destroy]
  resources :tokens 
  get 'status_search' ,  to:'tokens#status_search'
  get 'admin/admin'
  get 'approve_status', to: 'admin#approve_appointment'
  resources :models, except: [:show]
  resources :kilometer_drivens, except: [:show]
  resources :variants, except: [:show]
 
  resources :registration_years, only: [:index]
  resources :registration_states, except: [:show]
  resources :brands, except: [:show]
  resources :cities, except: [:show]
  resources :sellers do 
              collection do
                get 'search_city'
                get 'search_brand'
                get 'search_registration_year'
                get 'search_variant'
                get 'search_registration_state'
                get 'search_kilometer_driven'
                get 'search_model'
                get 'update_status'
                get 'my_add'

              end
              member do
                get :toggle_status
                get :approve
                get :reject
              end
            end
  resources :users, except: [:new,:show] do
    member do
      get 'confirm_email'
    end
  end
  get '/signup', to: 'users#new'
  root to: 'pages#home'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_category_search.html.erb
<h1 align="center" class=" card-header my-4">Buy Car</h1>
<%= link_to 'All post', sellers_path, class: "btn btn-info btn-lg" %>
<%if logged_in? &&  (current_user.role.roles == "ADMIN" || current_user.role.roles == "BUYER") %>
    <%= form_tag sellers_path, method: :get do %>
      <p>
        <%= text_field_tag :search, params[:search], placeholder: "search" %>
        <%= button_tag "Search", name: nil, class: "btn btn-dark" %>
      </p>
    <%end%>
<% end %>
  <%= form_tag search_city_sellers_path, method: 'get' do %>
    <%= select_tag "city_name", options_from_collection_for_select(City.all, "name", "name",selected: params[:city_name]), onchange:  "this.form.submit();", prompt: "Search by city", class: "custom-select" %>          
    <%= select_tag "model_name", options_from_collection_for_select(Model.all, "name", "name",selected: params[:model_name]), onchange:  "this.form.submit();", prompt: "Search by model", class: "custom-select" %>      
    <%= select_tag "brand_name", options_from_collection_for_select(Brand.all, "name", "name",selected: params[:brand_name]), onchange: "this.form.submit();", prompt: "Search by brand", class: "custom-select" %>      
    <%= select_tag "registration_year_name", options_from_collection_for_select(RegistrationYear.all, "name", "name",selected: params[:registration_year_id]), onchange: "this.form.submit();", prompt: "Search by Registration Year", class: "custom-select" %>      
    <%= select_tag "kilometer_driven_name", options_from_collection_for_select(KilometerDriven.all, "name", "name",selected: params[:kilometer_driven_name]), onchange: "this.form.submit();", prompt: "Search by Kilometer Driven", class: "custom-select" %>      
    <%= select_tag "variant_name", options_from_collection_for_select(Variant.all, "name", "name",selected: params[:variant_name]), onchange: "this.form.submit();", prompt: "Search by Variant", class: "custom-select" %>      
    <%= select_tag "registration_state_name", options_from_collection_for_select(RegistrationState.all, "name", "name",selected: params[:registration_state_name]), onchange: "this.form.submit();", prompt: "Search by Registration State", class: "custom-select" %>      
  <% end %>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <script type="text/javascript">
    <% obj.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_nav.html.erb
<div class="bg-dark">
  <nav class="navbar container navbar-expand-lg navbar-dark">
  <%= link_to 'Car Place', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? &&  current_user.role.roles == "ADMIN" %>
      <li class="nav-item">
        <%= link_to 'Admin', admin_admin_path, class: 'nav-link' %>
      </li>
    <%end%>
    <% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        My account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Edit', edit_user_path(current_user), class: 'dropdown-item' %>
          <% if logged_in? && current_user.role.roles == "SELLER" %>
            <%= link_to 'My appointment', tokens_path, class: "dropdown-item" %>
            <%= link_to 'Branch', locations_path, class: "dropdown-item" %> 
            <form class="form-inline my-2 mx-2 my-lg-0" action="status_search">
              <input class="form-control mr-sm-2 my-2" type="search" name="q" placeholder="Appointment no" aria-label="Search">
              <button class="btn btn-outline-success my-2  my-sm-0" type="submit">Search appointment</button>
            </form>
          <%end%>
        </div>
      <% end %>
      </li>
    </ul> 
      <div class=" d-flex mx-3">
      <% if logged_in?%>
          <%= link_to 'Logout',logout_path, class: 'nav-link btn btn-outline-danger rounded-pill',method: :delete %>
        <% else %>
          <%= link_to 'Sign up',signup_path, class: 'nav-link btn btn-primary rounded-pill mx-3' %>
          <%= link_to 'Login',login_path, class: 'nav-link btn btn-light ' %>
        <%end%>
         <% if logged_in? &&  current_user.role.roles == "SELLER" %> 
           <%= link_to 'Buyer status', update_status_sellers_path, class: 'nav-link btn btn-outline-success rounded-pill ml-3' %>
        <%end%>
        <% if logged_in? &&  current_user.role.roles == "ADMIN" %> 
           <%= link_to 'Update appointment', approve_status_path, class: 'nav-link btn btn-outline-secondary rounded-pill ml-3' %>
        <%end%>
      </div> 
    </div>
  </nav>
</div>