config/routes.rb
Rails.application.routes.draw do
  resources :locations, except: [:show,:edit,:update,:destroy]
  resources :car_costs, except: [:show,:destroy]
  resources :tokens 
  get 'status_search' ,  to:'tokens#status_search'
  get 'admin/admin'
  get 'approve_status', to: 'admin#approve_appointment'
  resources :models, except: [:show]
  resources :kilometer_drivens, except: [:show]
  resources :variants, except: [:show]
 
  resources :registration_years, only: [:index]
  resources :registration_states, except: [:show]
  resources :brands, except: [:show]
  resources :cities, except: [:show]
  resources :sellers do 
              collection do
                get 'search_city'
                get 'search_brand'
                get 'search_registration_year'
                get 'search_variant'
                get 'search_registration_state'
                get 'search_kilometer_driven'
                get 'search_model'
                get 'update_status'
                get 'my_add'

              end
              member do
                get :toggle_status
                get :approve
                get :reject
              end
            end
  resources :users, except: [:new,:show] do
    member do
      get 'confirm_email'
    end
  end
  get '/signup', to: 'users#new'
  root to: 'pages#home'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/registration_state.rb
class RegistrationState < ApplicationRecord
  before_save :upcase_fields, if: :name?
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :sellers

  private
  
  def upcase_fields
    self.name.upcase!
  end
end

app/controllers/registration_states_controller.rb
class RegistrationStatesController < ApplicationController
  before_action :set_registration_state, only: [ :edit, :update, :destroy]
  before_action :require_login 
  before_action :require_admin

  def index
    @registrationstates = RegistrationState.all
  end

  def new
    @registrationstate = RegistrationState.new
  end

  def edit
  end

  def create
    @registrationstate = RegistrationState.new(registration_state_params)

    if @registrationstate.save
      redirect_to registration_states_path, notice: 'RegistrationState was successfully created.' 
    else
      render :new 
    end
  end

  def update
    if @registrationstate.update(registration_state_params)
      redirect_to registration_states_path, notice: 'RegistrationState was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @registrationstate.destroy

    redirect_to registration_states_url, notice: 'RegistrationState was successfully destroyed.' 
  end



  private

    def set_registration_state
      @registrationstate = RegistrationState.find(params[:id])
    end

    def registration_state_params
      params.require(:registration_state).permit(:name)
    end
end

app/views/registration_states/_form.html.erb
<%= form_with(model: registrationstate, local: true) do |form| %>
  <%= render 'shared/error', obj: @registrationstate %>
  <div class="field card-body">
    <%= form.label :name  %>
    <%= form.text_field :name, placeholder: 'Enter Registration State' %>
  </div>
  <div class="actions text-center">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/registration_states/edit.html.erb
<div class="text-center">
	<h1 class="card-header">Edit City</h1>
	<%= render 'form', registrationstate: @registrationstate %>
	<%= link_to 'Back', registration_states_path, class: 'btn btn-dark m-4' %>
</div>

app/views/registration_states/index.html.erb
<h1 class="text-center card-header">RegistrationState index </h1>

<div class="card-header text-center">
  <%= link_to 'Add new Registrationstate', new_registration_state_path , class: 'btn btn-primary my-4' %>
</div>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>
  <tbody>
  <% @registrationstates.each do |registrationstate| %>
    <tr>
      <td><%= registrationstate.name  %></td>
      <td><%= link_to 'Edit', edit_registration_state_path(registrationstate), class: 'btn btn-warning '  %></td>
      <td><%= link_to 'Destroy', registrationstate, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger '  %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/registration_states/new.html.erb
<div class=" card-header my-4 text-center"> <h1>Add New Registrationstate</h1> </div>

<%= render 'form', registrationstate: @registrationstate %>

<div class="text-center">
	<%= link_to 'Back', cities_path , class: " btn btn-dark" %>
</div>